name: Generate keys
on: push
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install
      - name: npm ci and npm run keys
        run: |
          npm ci
          npm run keys
        env:
          CI: true
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: stage keys file
        run: git add src/keys.json
      - name: commit keys
        run: git commit -m "Auto updating keys.json"
      - name: fetch from main
        run: git fetch origin main 
      - name: push code to main
        run: git push origin HEAD:main
