name: Generate keys
on: push
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install
      - name: npm ci and npm run keys
        run: |
          git remote set-url origin git@github.com:giammirove/videogatherer.git
          npm ci
          npm run keys 
          ls -la src/
        env:
          CI: true
      - name: checking status
        run: git status
      - name: setting identity
        run: |
          git config --global user.email "rovelli.gianmarai@gmail.com"
          git config --global user.name "Gianmaria Rovelli"
      - name: stage keys file
        run: git add src/keys.json
      - name: commit keys
        run: git commit -m "Updating keys.json"
      - name: fetch from main
        run: git fetch origin main 
      - name: push code to main
        run: git push origin HEAD:main
